### PR TITLE
143451211 additional accessibility fixes

### PR DESCRIPTION
**Pull request by mollybrown**
This branch implements the following accessibility fixes/concerns:

1. Add lang attribute to <html> element
2. Add aria-label attribute to all form fields without an explicit label (ex: email field for newsletter signup on footer)
3. Ensure that all <li> elements are children of  `<ul>` or `<ol>` elements on alumni show page

### CODE REVIEW

**Comment by drod1000** [comment]
@mollybrown Looks good to me!

**Comment by neight-allen** [comment]
Nice work 🎉

**Comment by Laszlo-JFLMTCO** [comment]
@mollybrown Thank for tirelessly working on improving site responsiveness!!! I am  ok to merge these improvements.

**Comment by jdconrad89** [comment]
@mollybrown everything looks good to me! Thanks for taking care of this!

**Pull request merged**
