### PR TITLE
142655573 remove favorites

### PR DESCRIPTION
**Pull request by drod1000**

### CODE REVIEW

**Comment by drod1000** [comment]
@jdconrad89 @mollybrown @Laszlo-JFLMTCO 
Removes heart functionality and icons, along with related styling and tests. I also removed the guest jumbo component which I realized was not being used when went through the classes with hearts.
@neight-allen

**Comment by mollybrown** [comment]
Looks good! You weren't kidding when you said there were a lot of files you were going to need to change to make this happen!

**Comment by Laszlo-JFLMTCO** [comment]
@drod1000 Thank you for the effort! Nice cleanup! So apparently it seems that the `favorite` selections were not saved anywhere, but were only temporary while a visitor was on that page. Is that correct? As none of the changes seems to have any impact on saving data either in the `session` and/or in the `database`. Is my understanding correct?

**Comment by drod1000** [comment]
@Laszlo-JFLMTCO Correct! I went through the schema to see if it was being stored anywhere but I couldn't find anything. As far as I can tell it they were only keeping track of them temporarily.

**Comment by jdconrad89** [comment]
@drod1000 Thank you for doing this, there was quite a lot of stuff to weed out for this card!

**Pull request merged**
