### PR TITLE
142555565 random portfolios

### PR DESCRIPTION
**Pull request by Laszlo-JFLMTCO**
@jdconrad89 @mollybrown @drod1000 

This PR addresses [ticket ID 142555565](https://www.pivotaltracker.com/story/show/142555565).

IMPORTANT: Alumni portfolios are displayed in random order. Test is `skipped` due to general test setup issue documented under [ticket id 143533323](https://www.pivotaltracker.com/story/show/143533323)
Also `skipped` the A-Z sorting test, which now gives inconsistent results due to the starting point being a randomized list.

FYI @neight-allen

### CODE REVIEW

**Comment by neight-allen** [comment]
This contains code that hasn't yet been accepted and merged. This makes it harder to look at your change, since I have to mentally filter out the code that's from another PR.

In the future, branch from staging, and don't merge in changes that haven't yet been accepted as a PR.

**Comment by Laszlo-JFLMTCO** [comment]
@neight-allen I agree, although I am not sure how the non merged code made it into this branch as I branched off of `development` as we usually do.

Update: I just realized the PR was submitted to `master` instead of `development`. I just fixed that and the additional commits are gone now. Sorry for the confusion. Thought it is still strange how come that some commits are in `master` already which are not included in `development`.

FYI @jdconrad89 @drod1000 @mollybrown

**Comment by jdconrad89** [comment]
@Laszlo-JFLMTCO if I remember correctly I think there were a few things that needed a quick fix so they merged it directly into master. Everything looks good to me, I'm good to merge this if no one has any glaring comments or requests.

**Comment by drod1000** [comment]
@Laszlo-JFLMTCO Looks good to me.

**Comment by mollybrown** [comment]
@Laszlo-JFLMTCO looks good to me as well. Also, this is the first time I've seen the .shuffle function... yay for learning something new.

**Pull request merged**
