### PR TITLE
File uploads and bug fixes before presentation

### PR DESCRIPTION
**Pull request by MDes41**
File uploads for images with s3 and paperclip
Projects edit buttons
Projects delete buttons
Got Rid of debuggers
Add paperclip
Fixed alumni show
Made profiles dynamic to user
Passed down avatar props to component

*Could not figure out kramdown

### CODE REVIEW

**Comment by MDes41** [comment]
@neight-allen ready for review

**Comment by neight-allen** [comment]
1. What have you tried with kramdown? Can you put some code snippets in a comment?
2. Since this is such a big PR, can you use this template: https://quickleft.com/blog/pull-request-templates-make-code-review-easier/

**Comment by neight-allen** [comment]
Ok, we talked about the markdown problems. And I'm going to go ahead and merge this, and we'll look for refactor opportunities later.
But get rid of those damn debuggers first. @dshinzie @antciccone @MDes41

**Comment by dshinzie-zz** [comment]
@neight-allen debuggers have been removed. ready for merge

**Pull request merged**
